--liquibase formatted sql

--changeset nalemian:create-seq
CREATE SEQUENCE IF NOT EXISTS accounts_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS book_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;