server:
  port: 9999

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/mydb
    username: mkyong
    password: password
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      datasource:
        url: jdbc:postgresql://localhost:5432/mydb
        username: mkyong
        password: password
        driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# app custom property, if true, insert data for testing
app:
  db:
    init:
      enabled: true